[build]
publish = "public"
command = "npm run build"
[[plugins]]
  package = 'netlify-plugin-search-index'
  [plugins.inputs]
    generatedFunctionName = 'mySearchIndex'
    publishDirJSONFileName = 'mySearchIndex' # you can use / to nest in a directory


