[build]
publish = "public"
command = "npm run build"
[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['main', 'develop', 'feat/add-algolia']
  disabled = true
  pathPrefix = "/docs"
  customDomain = "bgoonz-blog.netlify.app/"
  renderJavaScript = true
