[build]
publish = "public"
command = "npm run build"
pagesDir= "src/pages"
[functions]
  # Directory with serverless functions, including background functions,
  # to deploy. This is relative to the base directory if one has been set, 
  # or the root directory if a base hasn’t been set.
  directory = "functions/"
[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['master', 'preview']
  disabled = false
  pathPrefix = "/"
  customDomain = "https://bgoonz-blog.netlify.app/"
  renderJavaScript = true

